utils::globalVariables(c("dt", "lon1", "lat1", "x1", "y1", "x.se1", "y,se1",
       "diag", "meta", "dive_se", "ctd_se", "tmp", "tmp1",
       "my.aes", "n", "flocs", "locs", "end.locs", "olocs",
       "dd", "p.lat", "p.lon", "source", "dest", "url",
       "h", "cd", "base_name", "full_path", "SMRUCampaignID",
       "tag_mfr", "tm", "device_id", "device_wmo_ref", "tag_type",
       "common_name", "species", "release_longitude", "release_latitude",
       "release_site", "release_date", "recovery_date", "age_class",
       "sex", "actual_mass", "ref", "de_date", "max_dep", "end_date",
       "Date", "Start", "End", "dive_start", "dive_end", "id",
       "g", "keep", ".", "d_date", "s_date", "e_date", "s_date_tag",
       "e_date_tag", "created", "modified", "ds_date", "de_date_tag",
       "surf_tm", "dive_tm", "haul_tm", "DeploymentID",
       "DeploymentStartDateTime", "lat.x", "lon.x", "lat.y", "lon.y",
       "x", "y", "x_se", "y_se", "ssm_lon", "ssm_lat", "ssm_x",
       "ssm_y", "ssm_x_se", "ssm_y_se", "lq", "lon", "lat",
       "semi_major_axis", "semi_minor_axis", "ellipse_orientation",
       "lc","smaj","smin","eor","ctd_start", "ctd_end", "dive_start",
       "dive_end", "DeploymentStopDateTime", "spcodes",
       "AnimalScientificName", "code", "sp", "cid", "d_sf",
       "u", "v", "u_se", "v_se", "s", "s_se", "qc_start_date",
       "qc_end_date", "packageVersion", "sattag_program", "AnimalAphiaID",
       "DeploymentLocation", "n_cond", "wet_n", "wet_min", "wet_max",
       "wet_mean", "wet_sd", "release_site", "state_country",
       "ptt", "Day", "Time", "owner", "status", "tag", "last_update_date",
       "Quality","Longitude","Latitude","dt.meta", "dt.dive","dist","dt",
       "spd","test","ADRProjectID","DiveStart","SegmentStart","EndMax",
   "proj4string","irapID","TagID","TagModel", "Age", "AgeClass", "CV_L",
    "DeployID", "G1",  "G2",  "G3",
   "G4",  "G5",  "G6",  "Lat", "Location", "Long", "M_est",
   "Mass", "Month",    "Name", "PTT", "STD_L",    "Sex", "Species",
   "TDeploy",  "Unittype", "WMO", "Year", "ageclass", "d.date",   "day",
   "de.date",  "deploy_date", "deployment",   "e.date",   "end.date", "estimated_mass", "gap",
   "geometry", "iq",  "latest_argos_location", "latest_uplink","location", "long","m_est",
   "mass", "month",    "parameters",   "quantile", "read.csv", "read.delim",    "reference",
   "round_date",    "s.date",   "smru_ref", "start_date",    "std_l",    "tdeploy",  "tdr_ctdid",
   "time", "unittype", "wmo", "x.se", "y.se", "year", "latest_gps", "HistType", "QC_start_date",
   "QC_end_date", "QC_end_datetime", "is_tag_serial", "Error radius", "embark_date",
   "embark_longitude", "embark_latitude", "deploy_lon", "deploy_lat", "QC_start_datetime",
   "sattag_program.x", "tag_model", "tag_serial_number", "tag_ptt", "release_location",
   "longitude", "latitude", "curved_carapace_length", "curved_carapace_length_unit",
   "phosi_secs", "last_location", "program_number", "ptt_decimal", "location_date",
   "first_uplink_date", "last_uplink_date", "last_loc_date", "deploy_longitude",
   "deploy_latitude", "last_loc_lon", "last_loc_lat", "i", "length_measurement",
   "length_unit", "mass_measurement", "mass_unit", "loc_meta","uuid"))
